In [117]:
import numpy as np
import pandas as pd
import gau_rff_python
import scipy

In [1]:
matrix = [[1, 2, 3, 4, 5],
          [0, 5, 4, 3, 2],
          [0, 0, 2, 3, 5]]

In [1]:
21*1 +21

42

In [138]:
matrix = pd.read_csv("matrix.csv", header=None).values
inv_matrix = np.linalg.pinv(matrix)
inv_matrix[400]

array([ 0.05092717,  0.16895525, -0.10119157,  0.47317088,  0.31039061,
        0.30879155, -0.09976176,  0.10683985, -0.66351407, -0.62534144,
       -0.02883811, -0.40631571, -0.17831678, -0.11762469,  0.9591336 ,
       -2.1170426 ,  0.14029185,  1.65321895, -0.83029014,  1.06042631])

In [134]:
r_mat = np.linalg.qr(matrix)[1]

In [135]:
svd_mat = scipy.linalg.svd(r_mat)

In [136]:
inv_mat = scipy.linalg.pinv(r_mat)

In [137]:
inv_mat[400]

array([ 0.04312533,  0.01136355, -0.0986258 , -0.08441183, -0.06808336,
        0.11934405, -0.24524255, -0.07848588,  0.06463192,  0.86391317,
        0.3751614 , -0.42626921,  0.08856352, -0.20239664, -0.66344938,
        1.68326248, -1.66471395, -0.06284892, -0.93741347,  1.82657808])

In [129]:
svd_mat[1]

array([4.36737714, 0.54036984, 0.5141974 , 0.4287249 , 0.34655583,
       0.32945209, 0.26961047, 0.21747656, 0.20255991, 0.18437202,
       0.16038277, 0.11079138, 0.10081741, 0.06167941, 0.05725894,
       0.0491159 , 0.04210133, 0.03581295, 0.01957808, 0.01594534])

In [108]:
svd_mat[2]

array([[-9.10399336e-03, -3.24570711e-02,  3.68038853e-02, ...,
        -3.81369843e-02, -1.23716951e-02,  4.29015401e-02],
       [-3.56712232e-02,  3.00242812e-02, -1.81188934e-02, ...,
         3.16632772e-02, -1.31773415e-02,  1.16045375e-02],
       [-5.29120933e-02, -2.88276255e-02, -1.81829829e-02, ...,
         3.91238288e-02,  7.11467896e-02,  7.95471590e-03],
       ...,
       [-1.36216440e-02, -2.87092905e-02,  3.63696060e-02, ...,
         8.78378207e-01, -1.31096383e-03,  4.71990546e-03],
       [ 8.60260783e-04, -2.97963353e-03,  8.46360128e-02, ...,
         2.64608981e-04,  9.76973945e-01,  4.80775342e-04],
       [ 5.72560314e-02, -3.28495700e-02, -1.07113031e-03, ...,
         3.78638278e-03, -4.30671648e-04,  9.80035801e-01]])

In [13]:
df = pd.read_csv("daily_vix.csv")
close = df["Close"].values

In [20]:
ret = lambda x: (x[1:]- x[:-1])/ x[:-1]
log_ret = lambda x: np.log(x[1:]/ x[:-1])

#lag matrix creation
lag_matrix = lambda x,lag: np.array([[x[j+i] for j in range(lag)] for i in range(len(x)-lag)])


In [21]:
n_lags = 14
ret_price = log_ret(close)
close_lag_mat = lag_matrix(ret_price, n_lags)